version: 2.1

orbs:
  python-ci: cjw296/python-ci@3.3.0

jobs:
  tests-linters:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: install dependencies & run tests
          command: |
            export POETRY_VERSION=1.3.1
            curl -sSL https://install.python-poetry.org | python3
            export PATH=/root/.local/bin:$PATH
            poetry config virtualenvs.create false
            poetry install --no-interaction --no-ansi
            python3 -m pytest
            poetry add black
            black --diff . && black --check .

workflows:
  test:
    jobs:
      - tests-linters
