version: 2.1

jobs:
  test & linters:
    docker:
      - image: cimg/python:3.10.2
    working_directory: ~/repo
    environment:
      POETRY_VERSION: 1.3.1
    steps:
      - checkout
      - run: |
          curl -sSL https://install.python-poetry.org | python3
          export PATH=/root/.local/bin:$PATH
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - run:
          name: Run pytest
          command: poetry run pytest
      - run:
          name: Run black
          command: |
            poetry black --diff .
            poetry run black --check .

workflows:
  version: 2
  build:
    jobs:
      - test & linters
