version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    working_directory: ~/repo
    environment:
      POETRY_VERSION: 1.3.1
    steps:
      - checkout
      - run: |
          curl -sSL https://install.python-poetry.org | python3
          source $HOME/.poetry/env
      - run: poetry install
      - run:
          name: Run pytest
          command: poetry run pytest
      - run:
          name: Run black
          command: poetry run black --check .

workflows:
  version: 2
  build:
    jobs:
      - build
