version: 2.1

orbs:
  python-ci: cjw296/python-ci@3.3.0

jobs:
  test:
    executor: python-ci/default # use the default executor specified by the orb
    steps:
      - checkout
      - python-ci/poetry-run-tests # Use a command from the orb in a job's

workflows:
  test:
    jobs:
      - test
