version: 2.1

jobs:
  tests-and-formatting:
    docker:
      - image: cimg/python:3.10.2
    environment:
      POETRY_VERSION: 1.3.1
    steps:
      - checkout
      - run:
          name: Install poetry and dependencies
          conmmand: |
            curl -sSL https://install.python-poetry.org | python3
            export PATH=/root/.local/bin:$PATH
            poetry config virtualenvs.create false
            poetry install --no-interaction --no-ansi
      - run:
          name: Run pytest
          command: poetry run pytest
      - run:
          name: Run black
          command: |
            poetry run black --check .
            poetry run black --diff .

workflows:
  version: 2
  build:
    jobs:
      - tests-and-formatting
