aws:
  region_name: eu-north-1
  secrets_names:
    - notion_client
    - fenix_mysql
  s3:
    bucket: fenix-notion-file-dump

display_columns:
  - Day
  - Time
  - Duration (min)
  - Status
  - Trainer
  - Weather
  - Tired
  - Trazadone
  - Recording
  - Date

trainers:
  40e597e9-749c-4703-b2ed-466f508c25a8: Seth
  5f909007-268c-43df-9a9d-65de1339e2f0: Kristia

status:
  Aced it: green
  Okay: orange
  Struggled: red
