aws:
  region_name: eu-north-1
  secrets_names:
    - notion_client

display_columns:
  - Duration (min)
  - Status
  - Date
  - Time
  - Trazadone
  - Tired
  - Weather
  - Recording
  - Trainer

trainers:
  40e597e9-749c-4703-b2ed-466f508c25a8: Seth
  5f909007-268c-43df-9a9d-65de1339e2f0: Kristia
